server:
  port: 10010 # 网关端口
spring:
  application:
    name: microservice-gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8849 # nacos地址
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      - id: service_consumer
        uri: lb://microservice-order
        predicates:
        - Path= /consumer/**
        filters:
        - StripPrefix=1